spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: ms-user
          uri:
            lb://ms-user
          predicates:
          - path=/api/users            
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
